### ISSUE TITLE
Allow for dynamically computing vectorial properties

### ISSUE THREAD

**Issue by bastonero** [aiidaplugins/aiida-lammps#114]
The current `parameters` for `LammpsCalculation` doesn't allow to specify vectorial `compute` properties, such as forces (fx, fy, fz) when computing `porperty/atom` for instance. This would be great to have instead of the `LammpsRawCalculation`, which is less appealing  when used as part of other automated workflows.

**Comment by JPchico** [comment]
Hi @bastonero I've been looking at this, and it turns out that I already had implemented this capability, it was mostly a miss categorization of this property.

The only problem now is to ensure that the formatting is proper, basically if you have a dynamic array in which you do not know the size the line that sets the string format runs into problem. I'm seeing how to fix this, but there is a chance that it might be fixable in an easy way.

**Comment by JPchico** [comment]
@bastonero If you want you can test with my [fork](https://github.com/JPchico/aiida-lammps/tree/114-allow-for-dynamically-computing-vectorial-properties). I tested with the example in the discourse that you put and it seems to work, but please let me know if it works okay now. 

Cheers

**Comment by bastonero** [comment]
@JPchico thanks a lot, I tried it out and it works (I just have to double check it parses it correctly, but it seems fine)

**Comment by JPchico** [comment]
Great! Let me know if in your other tests it works fine, of that way we can merge this and maybe make a newer release so that the pypi package is up to date.

**Comment by bastonero** [comment]
Hi @JPchico, I am! The calculations report what I need, so by now I don't anything to report. If something else won't work, I guess can be implemented by a later PR. Thanks a lot!
