### ISSUE TITLE
:books: Docs: Documentation overhaul

### ISSUE THREAD

**Issue by JPchico** [aiidaplugins/aiida-lammps#77]
The documentation right now is quite barebones and the examples cam be a bit confusing. The idea is to make the documentation easier to understand, cleaner, but with enough depth to explain the key concepts, such as the potential, the different types of calculations, etc.

Any ideas or prefferences about this @chrisjsewell and @sphuber?

**Comment by sphuber** [comment]
We have been migrating to the docs approach popularized by Django among others of having, tutorials, how-to guides, more in depth topics and reference guides. This has been working well I would say for [`aiida-core`](https://aiida-core.readthedocs.io/en/latest/) and [`aiida-quantumespresso`](https://aiida-quantumespresso.readthedocs.io/en/latest/), although the later is very recent and very much in progress. The topics and reference guides may be a bit too detailed for this plugin in the beginning but we can start with tutorials and how-tos, which are the most improtant, and the others can be added later.

As for the examples: I would tend to integrate them in the documentation, providing them as downloadable links. Or can even go to executable notebooks using myst-nb. Think that is easier for the user and ourselves than having a separate folder with some example scripts in it.

**Comment by chrisjsewell** [comment]
@sphuber is referring to this https://diataxis.fr/ 😉
I like it, although I wouldn't be dogmatic about it.

And yeh the idea of writing tutorials as notebooks is that ideally they they are executed for each documentation build, so that:

1. it ensures they are always up to date with the package (and will fail if not)
2. users should be able to download and run them

A good example is this: https://aiida-qe-demo.readthedocs.io/en/latest/2_bands_workflow.html

**Comment by JPchico** [comment]
Closed via #86
